### ISSUE TITLE
Error to install gearman with php 8.2

### ISSUE THREAD

**Issue by igordeveloper** [php/pecl-networking-gearman#23]
I'm trying to install gearman and receive the result below.

```
RUN pecl install gearman-2.1.0
4.260 pecl/gearman requires PHP (version >= 7.0.0, version <= 8.1.99, excluded versions: 6.0.0), installed version is 8.2.9
4.260 No valid packages found
4.260 install failed
```
Could you please relase a version with support for php 8.2 or help me how to proceed .

thank you.

**Comment by easterism** [comment]
@igordeveloper You can try this package https://packages.debian.org/bookworm/php8.2-gearman

**Comment by mlocati** [comment]
I can confirm that version 2.1.2 can be installed with PHP 8.2 and PHP 8.3.

Since it's not (yet) published [on the pecl website](https://pecl.php.net/package/gearman) you can't use `pecl` to install it.

For PHP docker images, you can use [my `install-php-extensions` script](https://github.com/mlocati/docker-php-extension-installer) though:

```sh
install-php-extensions php/pecl-networking-gearman@gearman-2.1.2
```

**Comment by mlocati** [comment]
I'd keep this issue open until a new version is published on pecl.php.net
