### ISSUE TITLE
Gearman's introductory demo does not recognize the "do" function

### ISSUE THREAD

**Issue by tree28** [php/pecl-networking-gearman#27]
Hello,

Some background and then the error followed by an observation:

Background: 
I am running php 8.3 on a fresh ubuntu 24.04 lts server, hosted at AWS. After successfully installing Gearman and receiving the version per the php getting started instructions given [here](https://gearman.org/getting-started/). I tried to run the first demo and received the following output.

Error:
**_PHP Warning:  Module "gearman" is already loaded in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined method GearmanClient::do() in /var/www/_gc_gearman.php:4
Stack trace:
#0 {main}_**

Observation: 
I then tried another example (the reverse example) from [here](http://gearman.org/examples/reverse/), which worked without a problem. I believe there is a bug in the extension or the "do" command is old and requires updating.

**Comment by esabol** [comment]
If your issue is about the web page on gearman.org being incorrect or outdated (the method should be `doNormal`, I guess), then you've submitted your issue to the wrong repository. The correct repository for such an issue is

https://github.com/gearman/gearman.github.io

Better yet, feel free to submit a PR to that repository. The file to edit is plain text (markdown). If that's the case, please close this issue as it is not relevant to this repository.

On the other hand, if your issue is that the PHP Gearman extension should support a `do` method (presumably an alias for `doNormal`?) in order to maintain backwards compatibility with older versions of the PHP Gearman extension, then you should leave this issue open and edit the original post and/or title to clarify.

**Comment by tree28** [comment]
Thanks.
Re-reported and closed.
