### ISSUE TITLE
Gearadmin query question

### ISSUE THREAD

**Issue by tree28** [php/pecl-networking-gearman#30]
Hello,
I have a question regarding the behavior of Gearadmin.

**Background** 
I am running Gearman on an AWS instance (ie. Instance A) with the private ip `10.0.3.1`

**Observation** 
I have noticed that Gearadmin will only return errors when performing a status query without the localhost ip of `127.0.0.1`

ie. 
`gearadmin -h 127.0.0.1 -p 4730 --status`
`reverse	0	0	1`

ie.
`gearadmin -h 10.0.3.1 -p 4730 --status`
`Error: Error connecting to 10.0.3.1.`

Why does this happen?

**Comment by esabol** [comment]
This is the GitHub repository for the Gearman PHP extension only, so this isn't the appropriate place for your question. It's not an issue with Gearman PHP extension, so you should close this issue, please.

The gearadmin command is part of the package of gearmand, the Gearman Job Server. The GitHub repository for that is https://github.com/gearman/gearmand/. That said, I would just be the one who ends up responding to you over there. :smile:

If you have the `nc` command (a.k.a. netcat) installed (or can install it), you can test connectivity to the gearmand server using the following command:

`(echo status ; sleep 0.1) | nc 10.0.4.1 4730 -w 1`

If that command works and `gearadmin -h 10.0.4.1 -p 4730 --status` doesn't, then I don't know what the problem could be....

One suggestion I have might to have your gearmand server listen to 0.0.0.0 instead of 127.0.0.1. Read this:

https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

**Comment by tree28** [comment]
Thank you @esabol – will revise and resubmit.

**Comment by tree28** [comment]
@esabol 
A brief followup question: I looked through the Gearman documentation but could not see notes or an example for how to configure the server to listen to 0.0.0.0 - would you mind pointing me in the right direction?

**Comment by esabol** [comment]
It's the `--listen` argument. https://gearman.org/gearmand/gearmand/

But it defaults to 0.0.0.0, so if you didn't know that, I doubt you changed it.
